services:
  - docker

script:
  - docker build -t app .
  - docker run --rm app sh -c "./cc-test-reporter before-build && gocov test ./... -coverprofile=c.out && ./cc-test-reporter after-build --exit-code 0"

